[tmp] Removed broken setup on travis.ci
The ruby-hean and jruby-head builders
do not respect bundler version.
https://travis-ci.org/mshytikov/named_struct/jobs/116899421
Bundler version 1.6.9
Which has a bug with
```
NoMethodError: undefined method `spec' for nil:NilClass
```